export const courseData = [
  {
    id: 1,
    category: "html",
    title: "HTML Fundamental",
    description: "Pelajari dasar-dasar HTML5 dari struktur dokumen hingga semantic elements. Kursus ini mencakup form, multimedia, table, dan best practices untuk web accessibility.",
    duration: "4-6 minggu",
    level: "Beginner",
    modules: 12,
    lessons: 48,
    projects: 5,
    price: 0, // FREE course
    originalPrice: 299000,
    rating: 4.8,
    students: 1250,
    instructor: "Nicholian Tjuarsa",
    isLocked: false,
    isFree: true,
    topics: [
      "HTML5 Structure & Syntax",
      "Semantic HTML Elements",
      "Forms & Input Validation",
      "Tables & Data Presentation",
      "Media & Embedding",
      "Accessibility Best Practices",
      "SEO Fundamentals",
      "HTML5 APIs"
    ],
    prerequisites: [],
    certificate: true,
    language: "Indonesia",
    subtitles: true,
    features: [
      "Downloadable resources",
      "Assignments with feedback",
      "Certificate of completion",
      "Lifetime access"
    ]
  },
  {
    id: 2,
    category: "css",
    title: "CSS Styling & Layout",
    description: "Master CSS3 dari basic styling hingga advanced layout techniques. Pelajari Flexbox, Grid, animations, responsive design, dan modern CSS features.",
    duration: "4-6 minggu",
    level: "Beginner",
    modules: 14,
    lessons: 56,
    projects: 6,
    price: 0, // FREE course
    originalPrice: 349000,
    rating: 4.9,
    students: 980,
    instructor: "Anggara Adelee",
    isLocked: false,
    isFree: true,
    topics: [
      "CSS Fundamentals & Selectors",
      "Box Model & Typography",
      "Flexbox Layout",
      "CSS Grid Layout",
      "Responsive Design Principles",
      "CSS Animations & Transitions",
      "Custom Properties & Variables",
      "Modern CSS Features"
    ],
    prerequisites: ["HTML Fundamental"],
    certificate: true,
    language: "Indonesia",
    subtitles: true,
    features: [
      "Downloadable resources",
      "Interactive coding exercises",
      "Certificate of completion",
      "Lifetime access"
    ]
  },
  {
    id: 3,
    category: "js",
    title: "JavaScript Dasar",
    description: "Pelajari JavaScript dari nol hingga intermediate. Dari variabel, function, DOM manipulation, hingga ES6+ features dan asynchronous programming.",
    duration: "6-8 minggu",
    level: "Intermediate",
    modules: 18,
    lessons: 72,
    projects: 8,
    price: 499000,
    originalPrice: 649000,
    rating: 4.7,
    students: 750,
    instructor: "Ethan Wilbert",
    isLocked: true,
    isFree: false,
    topics: [
      "JavaScript Fundamentals",
      "Functions & Scope",
      "DOM Manipulation",
      "Event Handling",
      "ES6+ Features",
      "Async JavaScript",
      "Error Handling & Debugging",
      "Modern JavaScript Patterns"
    ],
    prerequisites: ["HTML Fundamental", "CSS Styling"],
    certificate: true,
    language: "Indonesia",
    subtitles: true,
    features: [
      "Downloadable resources",
      "Coding challenges",
      "Certificate of completion",
      "Lifetime access",
      "1-on-1 mentorship"
    ]
  },
  {
    id: 4,
    category: "bootstrap",
    title: "Bootstrap Framework",
    description: "Master Bootstrap 5 untuk rapid development. Pelajari components, utilities, customization, dan best practices untuk professional web design.",
    duration: "2-3 minggu",
    level: "Intermediate",
    modules: 8,
    lessons: 32,
    projects: 3,
    price: 249000,
    originalPrice: 349000,
    rating: 4.6,
    students: 620,
    instructor: "Devin Owen Sanusi",
    isLocked: true,
    isFree: false,
    topics: [
      "Bootstrap Setup & Basics",
      "Layout System & Grid",
      "Bootstrap Components",
      "Utilities & Helpers",
      "Forms & Validation",
      "Customization & Theming",
      "Bootstrap with JavaScript",
      "Best Practices"
    ],
    prerequisites: ["HTML Fundamental", "CSS Styling"],
    certificate: true,
    language: "Indonesia",
    subtitles: true,
    features: [
      "Downloadable resources",
      "Project templates",
      "Certificate of completion",
      "Lifetime access"
    ]
  },
  {
    id: 5,
    category: "react",
    title: "React Development",
    description: "Pelajari React dari dasar hingga advanced. Component-based architecture, state management, hooks, routing, dan deployment ke production.",
    duration: "8-10 minggu",
    level: "Advanced",
    modules: 20,
    lessons: 80,
    projects: 10,
    price: 699000,
    originalPrice: 899000,
    rating: 4.8,
    students: 450,
    instructor: "Ethan Wilbert",
    isLocked: true,
    isFree: false,
    topics: [
      "React Fundamentals",
      "Components & Props",
      "State & Lifecycle",
      "React Hooks Deep Dive",
      "Context API",
      "React Router",
      "State Management with Redux",
      "Testing & Deployment"
    ],
    prerequisites: ["HTML Fundamental", "CSS Styling", "JavaScript Dasar"],
    certificate: true,
    language: "Indonesia",
    subtitles: true,
    features: [
      "Downloadable resources",
      "Real-world projects",
      "Certificate of completion",
      "Lifetime access",
      "Career support"
    ]
  }
];

export const additionalCourses = [
  {
    id: 6,
    category: "nodejs",
    title: "Node.js Backend Development",
    description: "Pelajari server-side JavaScript dengan Node.js. REST API, database, authentication, dan deployment ke cloud platforms.",
    duration: "8-10 minggu",
    level: "Advanced",
    modules: 16,
    lessons: 64,
    projects: 7,
    price: 599000,
    originalPrice: 799000,
    rating: 4.7,
    students: 320,
    instructor: "Ethan Wilbert",
    isLocked: true,
    isFree: false,
    topics: [
      "Node.js Fundamentals",
      "Express.js Framework",
      "RESTful API Design",
      "Database Integration",
      "Authentication & Security",
      "Testing & Debugging",
      "Deployment & DevOps",
      "Performance Optimization"
    ],
    prerequisites: ["JavaScript Dasar"],
    certificate: true,
    language: "Indonesia",
    subtitles: true,
    features: [
      "Downloadable resources",
      "API projects",
      "Certificate of completion",
      "Lifetime access"
    ]
  },
  {
    id: 7,
    category: "vue",
    title: "Vue.js Modern Development",
    description: "Master Vue.js 3 dengan Composition API. Pelajari reactive programming, component architecture, dan modern Vue ecosystem.",
    duration: "6-8 minggu",
    level: "Advanced",
    modules: 14,
    lessons: 56,
    projects: 6,
    price: 549000,
    originalPrice: 699000,
    rating: 4.6,
    students: 280,
    instructor: "Anggara Adelee",
    isLocked: true,
    isFree: false,
    topics: [
      "Vue.js Fundamentals",
      "Composition API",
      "Reactivity System",
      "Components & Props",
      "Vue Router",
      "State Management with Pinia",
      "Vue Ecosystem",
      "Testing & Deployment"
    ],
    prerequisites: ["HTML Fundamental", "CSS Styling", "JavaScript Dasar"],
    certificate: true,
    language: "Indonesia",
    subtitles: true,
    features: [
      "Downloadable resources",
      "Interactive projects",
      "Certificate of completion",
      "Lifetime access"
    ]
  },
  {
    id: 8,
    category: "typescript",
    title: "TypeScript Masterclass",
    description: "Upgrade JavaScript skills dengan TypeScript. Type safety, advanced types, generics, dan building scalable applications.",
    duration: "4-6 minggu",
    level: "Advanced",
    modules: 12,
    lessons: 48,
    projects: 5,
    price: 399000,
    originalPrice: 549000,
    rating: 4.8,
    students: 190,
    instructor: "Devin Owen Sanusi",
    isLocked: true,
    isFree: false,
    topics: [
      "TypeScript Fundamentals",
      "Type System Deep Dive",
      "Interfaces & Classes",
      "Generics & Advanced Types",
      "TypeScript with React",
      "TypeScript with Node.js",
      "Type Safety Best Practices",
      "Migration Strategies"
    ],
    prerequisites: ["JavaScript Dasar"],
    certificate: true,
    language: "Indonesia",
    subtitles: true,
    features: [
      "Downloadable resources",
      "Type-safe projects",
      "Certificate of completion",
      "Lifetime access"
    ]
  },
  {
    id: 9,
    category: "git",
    title: "Git & GitHub Workflow",
    description: "Master version control dengan Git. Collaboration, branching strategies, CI/CD, dan open source contribution best practices.",
    duration: "2-3 minggu",
    level: "Beginner",
    modules: 6,
    lessons: 24,
    projects: 3,
    price: 0, // FREE course
    originalPrice: 199000,
    rating: 4.5,
    students: 890,
    instructor: "Nicholian Tjuarsa",
    isLocked: false,
    isFree: true,
    topics: [
      "Git Fundamentals",
      "Branching & Merging",
      "Remote Repositories",
      "Collaboration Workflow",
      "GitHub Features",
      "CI/CD Basics",
      "Open Source Contribution",
      "Best Practices"
    ],
    prerequisites: [],
    certificate: true,
    language: "Indonesia",
    subtitles: true,
    features: [
      "Downloadable resources",
      "Git exercises",
      "Certificate of completion",
      "Lifetime access"
    ]
  },
  {
    id: 10,
    category: "docker",
    title: "Docker Containerization",
    description: "Pelajari containerization dengan Docker. Build, ship, dan run applications dengan Docker containers dan orchestration.",
    duration: "3-4 minggu",
    level: "Advanced",
    modules: 8,
    lessons: 32,
    projects: 4,
    price: 449000,
    originalPrice: 599000,
    rating: 4.7,
    students: 150,
    instructor: "Ethan Wilbert",
    isLocked: true,
    isFree: false,
    topics: [
      "Docker Fundamentals",
      "Container Management",
      "Dockerfile Best Practices",
      "Docker Compose",
      "Networking & Volumes",
      "Multi-stage Builds",
      "Container Orchestration",
      "Production Deployment"
    ],
    prerequisites: ["Node.js Backend Development"],
    certificate: true,
    language: "Indonesia",
    subtitles: true,
    features: [
      "Downloadable resources",
      "Container projects",
      "Certificate of completion",
      "Lifetime access"
    ]
  }
];

export const allCourses = [...courseData, ...additionalCourses];
